
auth.token=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

defaults.org=vaiouvem
defaults.project=react-native

defaults.url=https://sentry.io/
