name: CI

on:
  pull_request:
    branches: [main, develop]

jobs:
  health-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Tests
        run: npm test

      - name: Check Lint
        run: npm run lint
